name: CI

on:
  push:
    branches: [ master, main, develop, feature/**, hotfix/** ]
  pull_request:
    branches: [ master, main, develop ]

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: backend/package.json
      - name: Install backend deps
        working-directory: backend
        run: npm ci || npm install
      - name: Lint backend
        working-directory: backend
        run: npx eslint . --ext .js || echo 'Lint warnings only'
      - name: Test backend
        working-directory: backend
        env:
          NODE_ENV: test
        run: npx jest --coverage --runInBand
      - name: Upload coverage summary
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage
          path: backend/coverage/

  # Placeholder for future frontend job
  frontend-build:
    runs-on: ubuntu-latest
    if: false  # enable when frontend build pipeline ready
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package.json
      - name: Install frontend deps
        working-directory: frontend
        run: npm ci || npm install
      - name: Build frontend
        working-directory: frontend
        run: npm run build
